In [1]:
a=1
a

1

In [2]:
b=3
b

In [2]:
import stock_data as stock

scrapy = stock.Scrapy()
df = scrapy.get_TW_tickers(mode = "all")
df

d:\stock-main\stock_data.py:31: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(res.text)[0]
d:\stock-main\stock_data.py:31: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(res.text)[0]

0    market industry symbol name
0        上市     水泥工業   1101   台泥
1        上市     水泥工業   1102   亞泥
2        上市     水泥工業   1103   嘉泥
3        上市     水泥工業   1104   環泥
4        上市     水泥工業   1108   幸福
...     ...      ...    ...  ...
1807     上櫃    文化創意業   9949   琉園
1808     上櫃     塑膠工業   9950  萬國通
1809     上櫃     電機機械   9951   皇田
1810     上櫃     運動休閒   9960  邁達康
1811     上櫃     鋼鐵工業   9962   有益

[1812 rows x 4 columns]

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.1.4-cp312-cp312-win_amd64.whl.metadata (18 kB)
Collecting numpy<2,>=1.26.0 (from pandas)
  Downloading numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.2 kB 991.0 kB/s eta 0:00:01
     ---------------------------------------- 61.2/61.2 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\lib\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ---------------------------------------- 0.0/341.8 kB ? eta -:--:--
     ------------ ------------------------- 112.6/341.8 kB 3.2 MB/s eta 0:00:01
     ------------------------- ------------ 225.3/341.8 kB 3.4 MB/s eta 0:00:01
     -------------------------------------- 341.8/341.8 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in .\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.1.4-cp312-cp312-win_amd64.whl (10.5 MB)
   ---------------------------------------- 0.0/10.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.5 MB 3.6 MB/s eta 0:00:03
   - -------------------------------------- 0.3/10.5 MB 3.4 MB/s eta 0:00:03
   - -------------------------------------- 0.4/10.5 MB 3.4 MB/s eta 0:00:03
   -- ------------------------------------- 0.6/10.5 MB 3.3 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/10.5 MB 3.7 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/10.5 MB 3.6 MB/s eta 0:00:03
   ---- ----------------------------------- 1.1/10.5 MB 3.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/10.5 MB 3.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/10.5 MB 4.0 MB/s eta 0:00:03
   ------ --------------------------------- 1.8/10.5 MB 4.1 MB/s eta 0:00:03
   ------- -------------------------------- 2.0/10.5 MB 4.1 MB/s eta 0:00:03
   -------- ------------------------------- 2.3/10.5 MB 4.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.5/10.5 MB 4.3 MB/s eta 0:00:02
   ---------- ----------------------------- 2.8/10.5 MB 4.5 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/10.5 MB 4.6 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/10.5 MB 4.7 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/10.5 MB 4.8 MB/s eta 0:00:02
   --------------- ------------------------ 4.1/10.5 MB 5.0 MB/s eta 0:00:02
   ---------------- ----------------------- 4.4/10.5 MB 5.1 MB/s eta 0:00:02
   ------------------ --------------------- 4.8/10.5 MB 5.3 MB/s eta 0:00:02
   ------------------- -------------------- 5.2/10.5 MB 5.5 MB/s eta 0:00:01
   --------------------- ------------------ 5.6/10.5 MB 5.6 MB/s eta 0:00:01
   ----------------------- ---------------- 6.1/10.5 MB 5.8 MB/s eta 0:00:01
   ------------------------- -------------- 6.6/10.5 MB 6.0 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.5 MB 6.2 MB/s eta 0:00:01
   ----------------------------- ---------- 7.6/10.5 MB 6.4 MB/s eta 0:00:01
   ------------------------------ --------- 8.1/10.5 MB 6.6 MB/s eta 0:00:01
   --------------------------------- ------ 8.8/10.5 MB 6.8 MB/s eta 0:00:01
   ----------------------------------- ---- 9.4/10.5 MB 7.0 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.5 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  10.5/10.5 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------- 10.5/10.5 MB 7.6 MB/s eta 0:00:00
Downloading numpy-1.26.2-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   - -------------------------------------- 0.7/15.5 MB 21.1 MB/s eta 0:00:01
   --- ------------------------------------ 1.4/15.5 MB 14.5 MB/s eta 0:00:01
   ----- ---------------------------------- 2.1/15.5 MB 15.2 MB/s eta 0:00:01
   ------- -------------------------------- 3.0/15.5 MB 16.0 MB/s eta 0:00:01
   ---------- ----------------------------- 3.9/15.5 MB 16.7 MB/s eta 0:00:01
   ------------ --------------------------- 4.8/15.5 MB 17.9 MB/s eta 0:00:01
   -------------- ------------------------- 5.7/15.5 MB 18.4 MB/s eta 0:00:01
   ----------------- ---------------------- 6.7/15.5 MB 18.7 MB/s eta 0:00:01
   -------------------- ------------------- 7.8/15.5 MB 19.2 MB/s eta 0:00:01
   ----------------------- ---------------- 9.0/15.5 MB 19.9 MB/s eta 0:00:01
   -------------------------- ------------- 10.2/15.5 MB 20.4 MB/s eta 0:00:01
   ----------------------------- ---------- 11.6/15.5 MB 22.5 MB/s eta 0:00:01
   --------------------------------- ------ 12.9/15.5 MB 23.4 MB/s eta 0:00:01
   ------------------------------------ --- 14.3/15.5 MB 25.2 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 26.2 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 25.2 MB/s eta 0:00:00
Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
   ---------------------------------------- 0.0/502.5 kB ? eta -:--:--
   --------------------------------------- 502.5/502.5 kB 32.8 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.26.2 pandas-2.1.4 pytz-2023.3.post1 tzdata-2023.3

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import yfinance as yf
from tqdm import tqdm
from bs4 import BeautifulSoup
from chinese_calendar import is_workday
from io import StringIO
import requests, time, datetime, random, json

In [5]:
import stock_data as stock

scrapy = stock.Scrapy()
df = scrapy.get_price(
    start  = "2022-01-01",
    end = "2022-01-31",
    mode = "other",
    query = "2330.TW"
)
df

------------------------------ Get price. ------------------------------
[*********************100%%**********************]  1 of 1 completed
------------------------------ Clean data. ------------------------------

100%|██████████| 1/1 [00:00<00:00, 334.53it/s]

     Symbol       Date   Open   High    Low  Close  Adj Close    Volume
0   2330.TW 2022-01-03  619.0  632.0  618.0  631.0     604.63  69089158
1   2330.TW 2022-01-04  645.0  656.0  644.0  656.0     628.59  79434666
2   2330.TW 2022-01-05  669.0  669.0  646.0  650.0     622.84  69593809
3   2330.TW 2022-01-06  638.0  646.0  636.0  644.0     617.09  53210211
4   2330.TW 2022-01-07  643.0  646.0  632.0  634.0     607.51  38249908
5   2330.TW 2022-01-10  628.0  645.0  627.0  643.0     616.13  38289770
6   2330.TW 2022-01-11  646.0  651.0  639.0  651.0     623.80  33196585
7   2330.TW 2022-01-12  657.0  660.0  650.0  660.0     632.42  38860063
8   2330.TW 2022-01-13  658.0  662.0  655.0  661.0     633.38  38137411
9   2330.TW 2022-01-14  673.0  673.0  661.0  672.0     643.92  95200777
10  2330.TW 2022-01-17  685.0  688.0  678.0  683.0     654.46  59614236
11  2330.TW 2022-01-18  678.0  681.0  662.0  662.0     634.34  43593330
12  2330.TW 2022-01-19  652.0  660.0  651.0  654.0     626.67  40381333
13  2330.TW 2022-01-20  650.0  657.0  646.0  651.0     623.80  46474584
14  2330.TW 2022-01-21  644.0  646.0  637.0  641.0     614.22  49577684
15  2330.TW 2022-01-24  639.0  655.0  637.0  653.0     625.71  47134502
16  2330.TW 2022-01-25  643.0  645.0  638.0  641.0     614.22  52318736
17  2330.TW 2022-01-26  635.0  641.0  635.0  636.0     609.42  29957189